# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c547ccca21c77a2e4894a02c124a7b4"
name = "Gen AI SEO Product Description"
application_url = "https://ai-content-generation-nine.vercel.app"
embedded = true
handle = "gen-ai-seo-product-description"
[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

[app_proxy]
url = "https://ai-content-generation-nine.vercel.app/api/llms-txt"
subpath = "llms-txt"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_content,write_content,write_files,read_files,read_themes,write_themes,read_online_store_navigation,write_online_store_navigation"

[auth]
redirect_urls = [
  "https://ai-content-generation-nine.vercel.app/auth/callback",
  "https://ai-content-generation-nine.vercel.app/shopify/callback",
  "https://ai-content-generation-nine.vercel.app/api/auth/callback"
]
